

services:
  authentication-service:
    build:
      context: .
      dockerfile: AuthenticationTokenService/Dockerfile
    container_name: authentication-service
    ports:
      - "5000:8080" # Mở cổng 5000 cho dịch vụ
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
   
  