# Sử dụng hình ảnh .NET Core SDK để xây dựng ứng dụng
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Sao chép tất cả các tệp tin và thư mục từ thư mục gốc dự án vào /app trong container
COPY ["ApiGateWay/ApiGateWay/ApiGateWay.csproj","ApiGateWay/ApiGateWay/"]

RUN dotnet restore "ApiGateWay/ApiGateWay/ApiGateWay.csproj"

# Sao chép toàn bộ project và thư viện bên ngoài
COPY ApiGateWay/ApiGateWay "ApiGateWay/ApiGateWay/"


# Build project
WORKDIR "/app/ApiGateWay/ApiGateWay/"
RUN dotnet build "ApiGateWay.csproj" -c Release -o /app/build

# Publish project
FROM build AS publish
RUN dotnet publish "ApiGateWay.csproj" -c Release -o /app/publish

# Sử dụng image ASP.NET Core runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

# Thiết lập thư mục làm việc cho giai đoạn cuối
WORKDIR /app

# Sao chép các file đã publish từ giai đoạn build
COPY --from=publish /app/publish .

# Expose the port the app runs on
EXPOSE 8080

# Thiết lập entry point cho ứng dụng
ENTRYPOINT ["dotnet", "ApiGateWay.dll"]
